### ISSUE TITLE
Testing 1

### ISSUE THREAD

**Issue by charismaticx7** [drpresq/cacsupport#4]
cac support

**Comment by charismaticx7** [comment]
I keep having issues on line 13 and after running ./linux-*
./linux-cacsupport-base.sh: line 13: ./bootstrap: No such file or directory
./linux-cacsupport-base.sh: line 14: ./configure: No such file or directory. 

Initially I thought it was because I was missing bootstrap, but that didn't fix the issue. Still troubleshooting so far.

**Comment by drpresq** [comment]
Please provide the output of:
```
uname -a
```

```
apt list --installed
```

**Comment by charismaticx7** [comment]
Linux ubuntu 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


Listing...
accountsservice/focal-updates,focal-security,now 0.6.55-0ubuntu12~20untsservice/focal-updates,focal-security,now 0.6.55-0ubuntu12~20.04.4 amd64 [installed,automatic]
acl/focal,now 2.2.53-6 amd64 [installed,automatic]
acpi-support/focal,now 0.143 amd64 [installed,automatic]
acpid/focal,now 1:2.0.32-1ubuntu1 amd64 [installed,automatic]
adduser/focal,focal,now 3.118ubuntu2 all [installed,automatic]
adwaita-icon-theme/focal-updates,focal-updates,now 3.36.1-2ubuntu0.20.04.2 all [installed,automatic]
aisleriot/focal,now 1:3.22.9-1 amd64 [installed,automatic]
alsa-base/focal,focal,now 1.0.25+dfsg-0ubuntu5 all [installed,automatic]
alsa-topology-conf/focal,focal,now 1.2.2-1 all [installed,automatic]
alsa-ucm-conf/focal-updates,focal-updates,now 1.2.2-1ubuntu0.5 all [installed,automatic]
alsa-utils/focal-updates,now 1.2.2-1ubuntu2 amd64 [installed,automatic]
amd64-microcode/focal,now 3.20191218.1ubuntu1 amd64 [installed,automatic]
anacron/focal,now 2.3-29 amd64 [installed,automatic]
apg/focal,now 2.2.3.dfsg.1-5 amd64 [installed,automatic]
app-install-data-partner/focal,focal,now 19.04 all [installed,automatic]
apparmor/focal-updates,now 2.13.3-7ubuntu5.1 amd64 [installed,automatic]
apport-gtk/focal-updates,focal-updates,focal-security,focal-security,now 2.20.11-0ubuntu27.16 all [installed,automatic]
apport-symptoms/focal,focal,now 0.23 all [installed,automatic]
apport/focal-updates,focal-updates,focal-security,focal-security,now 2.20.11-0ubuntu27.16 all [installed,automatic]
appstream/focal,now 0.12.10-2 amd64 [installed,automatic]
apt-config-icons-hidpi/focal,focal,now 0.12.10-2 all [installed,automatic]
apt-config-icons/focal,focal,now 0.12.10-2 all [installed,automatic]
apt-utils/focal-updates,now 2.0.4 amd64 [installed,automatic]
apt/focal-updates,now 2.0.4 amd64 [installed,automatic]
aptdaemon-data/focal-updates,focal-updates,focal-security,focal-security,now 1.1.1+bzr982-0ubuntu32.3 all [installed,automatic]
aptdaemon/focal-updates,focal-updates,focal-security,focal-security,now 1.1.1+bzr982-0ubuntu32.3 all [installed,automatic]
apturl-common/focal,now 0.5.2ubuntu19 amd64 [installed,automatic]
apturl/focal,now 0.5.2ubuntu19 amd64 [installed,automatic]
aspell-en/focal,focal,now 2018.04.16-0-1 all [installed,automatic]
aspell/focal,now 0.60.8-1build1 amd64 [installed,automatic]
at-spi2-core/focal,now 2.36.0-2 amd64 [installed,automatic]
autoconf/focal,focal,now 2.69-11.1 all [installed]
automake/focal,focal,now 1:1.16.1-4ubuntu6 all [installed]
autotools-dev/focal,focal,now 20180224.1 all [installed,automatic]
avahi-autoipd/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
avahi-daemon/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
avahi-utils/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
baobab/focal,now 3.34.0-1 amd64 [installed,automatic]
base-files/focal-updates,now 11ubuntu5.3 amd64 [installed,automatic]
base-passwd/focal,now 3.5.47 amd64 [installed]
bash-completion/focal,focal,now 1:2.10-1ubuntu1 all [installed,automatic]
bash/focal-updates,now 5.0-6ubuntu1.1 amd64 [installed,automatic]
bc/focal,now 1.07.1-2build1 amd64 [installed,automatic]
bind9-dnsutils/focal-updates,now 1:9.16.1-0ubuntu2.4 amd64 [installed,automatic]
bind9-host/focal-updates,now 1:9.16.1-0ubuntu2.4 amd64 [installed,automatic]
bind9-libs/focal-updates,now 1:9.16.1-0ubuntu2.4 amd64 [installed,automatic]
binutils-common/focal,now 2.34-6ubuntu1 amd64 [installed,automatic]
binutils-x86-64-linux-gnu/focal,now 2.34-6ubuntu1 amd64 [installed,automatic]
binutils/focal,now 2.34-6ubuntu1 amd64 [installed,automatic]
bluez-cups/focal,now 5.53-0ubuntu3 amd64 [installed,automatic]
bluez-obexd/focal,now 5.53-0ubuntu3 amd64 [installed,automatic]
bluez/focal,now 5.53-0ubuntu3 amd64 [installed,automatic]
bolt/focal-updates,now 0.8-4ubuntu1 amd64 [installed,automatic]
branding-ubuntu/focal,focal,now 0.10 all [installed,automatic]
brltty/focal,now 6.0+dfsg-4ubuntu6 amd64 [installed,automatic]
bsdmainutils/focal,now 11.1.2ubuntu3 amd64 [installed,automatic]
bsdutils/focal-updates,now 1:2.34-0.1ubuntu9.1 amd64 [installed,automatic]
bubblewrap/focal,now 0.4.0-1ubuntu4 amd64 [installed,automatic]
build-essential/focal-updates,now 12.8ubuntu1.1 amd64 [installed]
busybox-initramfs/focal-updates,now 1:1.30.1-4ubuntu6.3 amd64 [installed,automatic]
busybox-static/focal-updates,now 1:1.30.1-4ubuntu6.3 amd64 [installed,automatic]
bzip2/focal,now 1.0.8-2 amd64 [installed,automatic]
ca-certificates/focal-updates,focal-updates,focal-security,focal-security,now 20210119~20.04.1 all [installed,automatic]
cheese-common/focal-updates,focal-updates,now 3.34.0-1ubuntu1 all [installed,automatic]
cheese/focal-updates,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
colord-data/focal,focal,now 1.4.4-2 all [installed,automatic]
colord/focal,now 1.4.4-2 amd64 [installed,automatic]
command-not-found/focal-updates,focal-updates,now 20.04.4 all [installed,automatic]
console-setup-linux/focal,focal,now 1.194ubuntu3 all [installed,automatic]
console-setup/focal,focal,now 1.194ubuntu3 all [installed,automatic]
coreutils/focal,now 8.30-3ubuntu2 amd64 [installed,automatic]
cpio/focal,now 2.13+dfsg-2 amd64 [installed,automatic]
cpp-9/focal-updates,focal-security,now 9.3.0-17ubuntu1~20.04 amd64 [installed,automatic]
cpp/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
cracklib-runtime/focal,now 2.9.6-3.2 amd64 [installed,automatic]
crda/focal,now 3.18-1build1 amd64 [installed,automatic]
cron/focal,now 3.0pl1-136ubuntu1 amd64 [installed,automatic]
cups-browsed/focal,now 1.27.4-1 amd64 [installed,automatic]
cups-bsd/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-client/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-common/focal-updates,focal-updates,focal-security,focal-security,now 2.3.1-9ubuntu1.1 all [installed,automatic]
cups-core-drivers/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-daemon/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-filters-core-drivers/focal,now 1.27.4-1 amd64 [installed,automatic]
cups-filters/focal,now 1.27.4-1 amd64 [installed,automatic]
cups-ipp-utils/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-pk-helper/focal,now 0.2.6-1ubuntu3 amd64 [installed,automatic]
cups-ppdc/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
cups-server-common/focal-updates,focal-updates,focal-security,focal-security,now 2.3.1-9ubuntu1.1 all [installed,automatic]
cups/focal-updates,focal-security,now 2.3.1-9ubuntu1.1 amd64 [installed,automatic]
dash/focal,now 0.5.10.2-6 amd64 [installed]
dbus-user-session/focal-updates,focal-security,now 1.12.16-2ubuntu2.1 amd64 [installed,automatic]
dbus-x11/focal-updates,focal-security,now 1.12.16-2ubuntu2.1 amd64 [installed,automatic]
dbus/focal-updates,focal-security,now 1.12.16-2ubuntu2.1 amd64 [installed,automatic]
dc/focal,now 1.07.1-2build1 amd64 [installed,automatic]
dconf-cli/focal,now 0.36.0-1 amd64 [installed,automatic]
dconf-gsettings-backend/focal,now 0.36.0-1 amd64 [installed,automatic]
dconf-service/focal,now 0.36.0-1 amd64 [installed,automatic]
debconf-i18n/focal,focal,now 1.5.73 all [installed,automatic]
debconf/focal,focal,now 1.5.73 all [installed,automatic]
debianutils/focal,now 4.9.1 amd64 [installed,automatic]
deja-dup/focal-updates,now 40.7-0ubuntu1 amd64 [installed,automatic]
desktop-file-utils/focal-updates,now 0.24-1ubuntu3 amd64 [installed,automatic]
dictionaries-common/focal,focal,now 1.28.1 all [installed,automatic]
diffutils/focal,now 1:3.7-3 amd64 [installed]
dirmngr/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
distro-info-data/focal-updates,focal-updates,focal-security,focal-security,now 0.43ubuntu1.4 all [installed,automatic]
dmidecode/focal,now 3.2-3 amd64 [installed,automatic]
dmsetup/focal,now 2:1.02.167-1ubuntu1 amd64 [installed,automatic]
dmz-cursor-theme/focal,focal,now 0.4.5ubuntu1 all [installed,automatic]
dns-root-data/focal,focal,now 2019052802 all [installed,automatic]
dnsmasq-base/focal-updates,focal-security,now 2.80-1.1ubuntu1.2 amd64 [installed,automatic]
docbook-xml/focal,focal,now 4.5-9 all [installed,automatic]
docbook-xsl/focal,focal,now 1.79.1+dfsg-2 all [installed]
dosfstools/focal,now 4.1-2 amd64 [installed,automatic]
dpkg-dev/focal,focal,now 1.19.7ubuntu3 all [installed,automatic]
dpkg/focal,now 1.19.7ubuntu3 amd64 [installed,automatic]
duplicity/focal,now 0.8.11.1612-1 amd64 [installed,automatic]
e2fsprogs/focal,now 1.45.5-2ubuntu1 amd64 [installed,automatic]
ed/focal,now 1.16-1 amd64 [installed,automatic]
eject/focal,now 2.1.5+deb1+cvs20081104-14 amd64 [installed,automatic]
emacsen-common/focal,focal,now 3.0.4 all [installed,automatic]
enchant-2/focal-updates,now 2.2.8-1ubuntu0.20.04.1 amd64 [installed,automatic]
eog/focal-updates,now 3.36.3-0ubuntu1 amd64 [installed,automatic]
espeak-ng-data/focal,now 1.50+dfsg-6 amd64 [installed,automatic]
evince-common/focal-updates,focal-updates,now 3.36.7-0ubuntu1 all [installed,automatic]
evince/focal-updates,now 3.36.7-0ubuntu1 amd64 [installed,automatic]
evolution-data-server-common/focal-updates,focal-updates,now 3.36.4-0ubuntu1 all [installed,automatic]
evolution-data-server/focal-updates,now 3.36.4-0ubuntu1 amd64 [installed,automatic]
fakeroot/focal,now 1.24-1 amd64 [installed,automatic]
fdisk/focal-updates,now 2.34-0.1ubuntu9.1 amd64 [installed,automatic]
file-roller/focal-updates,now 3.36.3-0ubuntu1 amd64 [installed,automatic]
file/focal,now 1:5.38-4 amd64 [installed,automatic]
findutils/focal,now 4.7.0-1ubuntu1 amd64 [installed]
firefox-locale-en/focal-updates,focal-security,now 85.0.1+build1-0ubuntu0.20.04.1 amd64 [installed]
firefox/focal-updates,focal-security,now 85.0.1+build1-0ubuntu0.20.04.1 amd64 [installed,automatic]
fontconfig-config/focal,focal,now 2.13.1-2ubuntu3 all [installed,automatic]
fontconfig/focal,now 2.13.1-2ubuntu3 amd64 [installed,automatic]
fonts-beng-extra/focal,focal,now 1.0-7 all [installed,automatic]
fonts-beng/focal,focal,now 2:1.2 all [installed,automatic]
fonts-dejavu-core/focal,focal,now 2.37-1 all [installed,automatic]
fonts-deva-extra/focal,focal,now 3.0-5 all [installed,automatic]
fonts-deva/focal,focal,now 2:1.2 all [installed,automatic]
fonts-droid-fallback/focal,focal,now 1:6.0.1r16-1.1 all [installed,automatic]
fonts-freefont-ttf/focal,focal,now 20120503-10 all [installed,automatic]
fonts-gargi/focal,focal,now 2.0-4 all [installed,automatic]
fonts-gubbi/focal,focal,now 1.3-3 all [installed,automatic]
fonts-gujr-extra/focal,focal,now 1.0.1-1 all [installed,automatic]
fonts-gujr/focal,focal,now 2:1.3 all [installed,automatic]
fonts-guru-extra/focal,focal,now 2.0-5 all [installed,automatic]
fonts-guru/focal,focal,now 2:1.2 all [installed,automatic]
fonts-indic/focal,focal,now 2:1.3 all [installed]
fonts-kacst-one/focal,focal,now 5.0+svn11846-10 all [installed,automatic]
fonts-kacst/focal,focal,now 2.01+mry-14 all [installed,automatic]
fonts-kalapi/focal,focal,now 1.0-3 all [installed,automatic]
fonts-khmeros-core/focal,focal,now 5.0-7ubuntu1 all [installed,automatic]
fonts-knda/focal,focal,now 2:1.2 all [installed,automatic]
fonts-lao/focal,focal,now 0.0.20060226-9ubuntu1 all [installed,automatic]
fonts-liberation2/focal,focal,now 2.1.0-1 all [installed,automatic]
fonts-liberation/focal,focal,now 1:1.07.4-11 all [installed,automatic]
fonts-lklug-sinhala/focal,focal,now 0.6-3 all [installed,automatic]
fonts-lohit-beng-assamese/focal,focal,now 2.91.5-1 all [installed,automatic]
fonts-lohit-beng-bengali/focal,focal,now 2.91.5-1 all [installed,automatic]
fonts-lohit-deva/focal,focal,now 2.95.4-4 all [installed,automatic]
fonts-lohit-gujr/focal,focal,now 2.92.4-4 all [installed,automatic]
fonts-lohit-guru/focal,focal,now 2.91.2-1 all [installed,automatic]
fonts-lohit-knda/focal,focal,now 2.5.4-2 all [installed,automatic]
fonts-lohit-mlym/focal,focal,now 2.92.2-1 all [installed,automatic]
fonts-lohit-orya/focal,focal,now 2.91.2-1 all [installed,automatic]
fonts-lohit-taml-classical/focal,focal,now 2.5.4-1 all [installed,automatic]
fonts-lohit-taml/focal,focal,now 2.91.3-1 all [installed,automatic]
fonts-lohit-telu/focal,focal,now 2.5.5-1 all [installed,automatic]
fonts-mlym/focal,focal,now 2:1.2 all [installed,automatic]
fonts-nakula/focal,focal,now 1.0-3 all [installed,automatic]
fonts-navilu/focal,focal,now 1.2-2 all [installed,automatic]
fonts-noto-cjk/focal,focal,now 1:20190410+repack1-2 all [installed,automatic]
fonts-noto-color-emoji/focal,focal,now 0~20200408-1 all [installed,automatic]
fonts-noto-mono/focal-updates,focal-updates,now 20200323-1build1~ubuntu20.04.1 all [installed,automatic]
fonts-opensymbol/focal-updates,focal-updates,now 2:102.11+LibO6.4.6-0ubuntu0.20.04.1 all [installed,automatic]
fonts-orya-extra/focal,focal,now 2.0-6 all [installed,automatic]
fonts-orya/focal,focal,now 2:1.2 all [installed,automatic]
fonts-pagul/focal,focal,now 1.0-7 all [installed,automatic]
fonts-sahadeva/focal,focal,now 1.0-4 all [installed,automatic]
fonts-samyak-deva/focal,focal,now 1.2.2-4 all [installed,automatic]
fonts-samyak-gujr/focal,focal,now 1.2.2-4 all [installed,automatic]
fonts-samyak-mlym/focal,focal,now 1.2.2-4 all [installed,automatic]
fonts-samyak-taml/focal,focal,now 1.2.2-4 all [installed,automatic]
fonts-sarai/focal,focal,now 1.0-2 all [installed,automatic]
fonts-sil-abyssinica/focal,focal,now 2.000-1 all [installed,automatic]
fonts-sil-padauk/focal,focal,now 4.000-1 all [installed,automatic]
fonts-smc-anjalioldlipi/focal,focal,now 7.1.2-1 all [installed,automatic]
fonts-smc-chilanka/focal,focal,now 1.400-1 all [installed,automatic]
fonts-smc-dyuthi/focal,focal,now 3.0.2-1 all [installed,automatic]
fonts-smc-gayathri/focal,focal,now 1.100-1 all [installed,automatic]
fonts-smc-karumbi/focal,focal,now 1.1.2-1 all [installed,automatic]
fonts-smc-keraleeyam/focal,focal,now 3.0.2-1 all [installed,automatic]
fonts-smc-manjari/focal,focal,now 1.710-1 all [installed,automatic]
fonts-smc-meera/focal,focal,now 7.0.3-1 all [installed,automatic]
fonts-smc-rachana/focal,focal,now 7.0.2-1 all [installed,automatic]
fonts-smc-raghumalayalamsans/focal,focal,now 2.2.1-1 all [installed,automatic]
fonts-smc-suruma/focal,focal,now 3.2.3-1 all [installed,automatic]
fonts-smc-uroob/focal,focal,now 2.0.2-1 all [installed,automatic]
fonts-smc/focal,focal,now 1:7.1 all [installed,automatic]
fonts-taml/focal,focal,now 2:1.3 all [installed,automatic]
fonts-telu-extra/focal,focal,now 2.0-4 all [installed,automatic]
fonts-telu/focal,focal,now 2:1.2 all [installed,automatic]
fonts-thai-tlwg/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tibetan-machine/focal,focal,now 1.901b-5 all [installed,automatic]
fonts-tlwg-garuda-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-garuda/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-kinnari-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-kinnari/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-laksaman-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-laksaman/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-loma-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-loma/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-mono-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-mono/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-norasi-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-norasi/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-purisa-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-purisa/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-sawasdee-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-sawasdee/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typewriter-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typewriter/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typist-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typist/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typo-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-typo/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-umpush-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-umpush/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-waree-ttf/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-tlwg-waree/focal,focal,now 1:0.7.1-3 all [installed,automatic]
fonts-ubuntu/focal,focal,now 0.83-4ubuntu1 all [installed,automatic]
fonts-urw-base35/focal,focal,now 20170801.1-3 all [installed,automatic]
fonts-yrsa-rasa/focal,focal,now 1.002-2 all [installed,automatic]
foomatic-db-compressed-ppds/focal,focal,now 20200401-1 all [installed,automatic]
fprintd/focal,now 1.90.1-1ubuntu1 amd64 [installed,automatic]
friendly-recovery/focal,focal,now 0.2.41 all [installed,automatic]
ftp/focal,now 0.17-34.1 amd64 [installed,automatic]
fuse/focal,now 2.9.9-3 amd64 [installed,automatic]
fwupd-signed/focal-updates,now 1.27.1ubuntu2+1.3.11-1~focal1 amd64 [installed,automatic]
fwupd/focal-updates,now 1.3.11-1~focal1 amd64 [installed,automatic]
g++-9/focal-updates,focal-security,now 9.3.0-17ubuntu1~20.04 amd64 [installed,automatic]
g++/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
gamemode/focal-updates,now 1.5.1-0ubuntu3.1 amd64 [installed,automatic]
gcc-10-base/focal-updates,focal-security,now 10.2.0-5ubuntu1~20.04 amd64 [installed,automatic]
gcc-9-base/focal-updates,focal-security,now 9.3.0-17ubuntu1~20.04 amd64 [installed,automatic]
gcc-9/focal-updates,focal-security,now 9.3.0-17ubuntu1~20.04 amd64 [installed,automatic]
gcc/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
gcr/focal,now 3.36.0-2build1 amd64 [installed,automatic]
gdb/focal-updates,now 9.2-0ubuntu1~20.04 amd64 [installed,automatic]
gdbserver/focal-updates,now 9.2-0ubuntu1~20.04 amd64 [installed,automatic]
gdisk/focal,now 1.0.5-1 amd64 [installed,automatic]
gdm3/focal-updates,now 3.36.3-0ubuntu0.20.04.3 amd64 [installed,automatic]
gedit-common/focal-updates,focal-updates,now 3.36.2-0ubuntu1 all [installed,automatic]
gedit/focal-updates,now 3.36.2-0ubuntu1 amd64 [installed,automatic]
genisoimage/focal,now 9:1.1.11-3.1ubuntu1 amd64 [installed,automatic]
geoclue-2.0/focal,now 2.5.6-0ubuntu1 amd64 [installed,automatic]
gettext-base/focal,now 0.19.8.1-10build1 amd64 [installed,automatic]
ghostscript-x/focal-updates,focal-security,now 9.50~dfsg-5ubuntu4.2 amd64 [installed,automatic]
ghostscript/focal-updates,focal-security,now 9.50~dfsg-5ubuntu4.2 amd64 [installed,automatic]
gir1.2-accountsservice-1.0/focal-updates,focal-security,now 0.6.55-0ubuntu12~20.04.4 amd64 [installed,automatic]
gir1.2-atk-1.0/focal,now 2.35.1-1ubuntu2 amd64 [installed,automatic]
gir1.2-atspi-2.0/focal,now 2.36.0-2 amd64 [installed,automatic]
gir1.2-dbusmenu-glib-0.4/focal,now 16.04.1+18.10.20180917-0ubuntu6 amd64 [installed,automatic]
gir1.2-dee-1.0/focal,now 1.2.7+17.10.20170616-4ubuntu6 amd64 [installed,automatic]
gir1.2-freedesktop/focal-updates,now 1.64.1-1~ubuntu20.04.1 amd64 [installed,automatic]
gir1.2-gck-1/focal,now 3.36.0-2build1 amd64 [installed,automatic]
gir1.2-gcr-3/focal,now 3.36.0-2build1 amd64 [installed,automatic]
gir1.2-gdesktopenums-3.0/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gir1.2-gdkpixbuf-2.0/focal-updates,focal-security,now 2.40.0+dfsg-3ubuntu0.1 amd64 [installed,automatic]
gir1.2-gdm-1.0/focal-updates,now 3.36.3-0ubuntu0.20.04.3 amd64 [installed,automatic]
gir1.2-geoclue-2.0/focal,now 2.5.6-0ubuntu1 amd64 [installed,automatic]
gir1.2-glib-2.0/focal-updates,now 1.64.1-1~ubuntu20.04.1 amd64 [installed,automatic]
gir1.2-gmenu-3.0/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gir1.2-gnomebluetooth-1.0/focal-updates,now 3.34.3-0ubuntu1 amd64 [installed,automatic]
gir1.2-gnomedesktop-3.0/focal-updates,now 3.36.8-0ubuntu1 amd64 [installed,automatic]
gir1.2-goa-1.0/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gir1.2-graphene-1.0/focal,now 1.10.0-1build2 amd64 [installed,automatic]
gir1.2-gst-plugins-base-1.0/focal,now 1.16.2-4 amd64 [installed,automatic]
gir1.2-gstreamer-1.0/focal,now 1.16.2-2 amd64 [installed,automatic]
gir1.2-gtk-3.0/focal-updates,now 3.24.20-0ubuntu1 amd64 [installed,automatic]
gir1.2-gtksource-4/focal,now 4.6.0-1 amd64 [installed,automatic]
gir1.2-gudev-1.0/focal,now 1:233-1 amd64 [installed,automatic]
gir1.2-gweather-3.0/focal-updates,now 3.36.1-1~ubuntu20.04.1 amd64 [installed,automatic]
gir1.2-ibus-1.0/focal-updates,now 1.5.22-2ubuntu2.1 amd64 [installed,automatic]
gir1.2-javascriptcoregtk-4.0/focal-updates,focal-security,now 2.30.3-0ubuntu0.20.04.1 amd64 [installed,automatic]
gir1.2-json-1.0/focal,now 1.4.4-2ubuntu2 amd64 [installed,automatic]
gir1.2-mutter-6/focal-updates,now 3.36.7+git20201123-0.20.04.1 amd64 [installed,automatic]
gir1.2-nm-1.0/focal-updates,now 1.22.10-1ubuntu2.2 amd64 [installed,automatic]
gir1.2-nma-1.0/focal-updates,now 1.8.24-1ubuntu3 amd64 [installed,automatic]
gir1.2-notify-0.7/focal,now 0.7.9-1ubuntu2 amd64 [installed,automatic]
gir1.2-packagekitglib-1.0/focal-updates,focal-security,now 1.1.13-2ubuntu1.1 amd64 [installed,automatic]
gir1.2-pango-1.0/focal,now 1.44.7-2ubuntu4 amd64 [installed,automatic]
gir1.2-peas-1.0/focal,now 1.26.0-2 amd64 [installed,automatic]
gir1.2-polkit-1.0/focal,now 0.105-26ubuntu1 amd64 [installed,automatic]
gir1.2-rb-3.0/focal,now 3.4.4-1ubuntu2 amd64 [installed,automatic]
gir1.2-rsvg-2.0/focal-updates,now 2.48.9-1ubuntu0.20.04.1 amd64 [installed,automatic]
gir1.2-secret-1/focal-updates,now 0.20.3-0ubuntu1 amd64 [installed,automatic]
gir1.2-snapd-1/focal-updates,now 1.58-0ubuntu0.20.04.0 amd64 [installed,automatic]
gir1.2-soup-2.4/focal,now 2.70.0-1 amd64 [installed,automatic]
gir1.2-totem-1.0/focal,now 3.34.1-2ubuntu2 amd64 [installed,automatic]
gir1.2-totemplparser-1.0/focal,now 3.26.5-1ubuntu1 amd64 [installed,automatic]
gir1.2-udisks-2.0/focal,now 2.8.4-1ubuntu1 amd64 [installed,automatic]
gir1.2-unity-5.0/focal,now 7.1.4+19.04.20190319-0ubuntu3 amd64 [installed,automatic]
gir1.2-upowerglib-1.0/focal,now 0.99.11-1build2 amd64 [installed,automatic]
gir1.2-vte-2.91/focal-updates,now 0.60.3-0ubuntu1~20.04 amd64 [installed,automatic]
gir1.2-webkit2-4.0/focal-updates,focal-security,now 2.30.3-0ubuntu0.20.04.1 amd64 [installed,automatic]
gir1.2-wnck-3.0/focal,now 3.36.0-1 amd64 [installed,automatic]
git-man/focal,focal,now 1:2.25.1-1ubuntu3 all [installed,automatic]
git/focal,now 1:2.25.1-1ubuntu3 amd64 [installed]
gjs/focal-updates,now 1.64.3-1~ubuntu20.04.1 amd64 [installed,automatic]
gkbd-capplet/focal,now 3.26.1-1 amd64 [installed,automatic]
glib-networking-common/focal-updates,focal-updates,focal-security,focal-security,now 2.64.2-1ubuntu0.1 all [installed,automatic]
glib-networking-services/focal-updates,focal-security,now 2.64.2-1ubuntu0.1 amd64 [installed,automatic]
glib-networking/focal-updates,focal-security,now 2.64.2-1ubuntu0.1 amd64 [installed,automatic]
gnome-accessibility-themes/focal,focal,now 3.28-1ubuntu1 all [installed,automatic]
gnome-bluetooth/focal-updates,now 3.34.3-0ubuntu1 amd64 [installed,automatic]
gnome-calculator/focal,now 1:3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-calendar/focal-updates,now 3.36.2-0ubuntu1 amd64 [installed,automatic]
gnome-characters/focal,now 3.34.0-1 amd64 [installed,automatic]
gnome-control-center-data/focal-updates,focal-updates,now 1:3.36.5-0ubuntu1 all [installed,automatic]
gnome-control-center-faces/focal-updates,focal-updates,now 1:3.36.5-0ubuntu1 all [installed,automatic]
gnome-control-center/focal-updates,now 1:3.36.5-0ubuntu1 amd64 [installed,automatic]
gnome-desktop3-data/focal-updates,focal-updates,now 3.36.8-0ubuntu1 all [installed,automatic]
gnome-disk-utility/focal,now 3.36.1-1ubuntu1 amd64 [installed,automatic]
gnome-font-viewer/focal,now 3.34.0-2 amd64 [installed,automatic]
gnome-getting-started-docs/focal-updates,focal-updates,now 3.36.2-0ubuntu0.1 all [installed,automatic]
gnome-initial-setup/focal-updates,now 3.36.2-0ubuntu2 amd64 [installed,automatic]
gnome-keyring-pkcs11/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-keyring/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-logs/focal-updates,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
gnome-mahjongg/focal,now 1:3.36.1-1 amd64 [installed,automatic]
gnome-menus/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-mines/focal,now 1:3.36.0-1 amd64 [installed,automatic]
gnome-online-accounts/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-power-manager/focal,now 3.32.0-2 amd64 [installed,automatic]
gnome-screenshot/focal,now 3.36.0-1ubuntu1 amd64 [installed,automatic]
gnome-session-bin/focal,now 3.36.0-2ubuntu1 amd64 [installed,automatic]
gnome-session-canberra/focal,now 0.30-7ubuntu1 amd64 [installed,automatic]
gnome-session-common/focal,focal,now 3.36.0-2ubuntu1 all [installed,automatic]
gnome-settings-daemon-common/focal-updates,focal-updates,now 3.36.1-0ubuntu1 all [installed,automatic]
gnome-settings-daemon/focal-updates,now 3.36.1-0ubuntu1 amd64 [installed,automatic]
gnome-shell-common/focal-updates,focal-updates,focal-security,focal-security,now 3.36.4-1ubuntu1~20.04.2 all [installed,automatic]
gnome-shell-extension-appindicator/focal-updates,focal-updates,now 33.1-0ubuntu0.20.04.1 all [installed,automatic]
gnome-shell-extension-desktop-icons/focal-updates,focal-updates,now 20.04.0-3~ubuntu20.04.1 all [installed,automatic]
gnome-shell-extension-ubuntu-dock/focal-updates,focal-updates,now 68ubuntu1~20.04.1 all [installed,automatic]
gnome-shell/focal-updates,focal-security,now 3.36.4-1ubuntu1~20.04.2 amd64 [installed,automatic]
gnome-startup-applications/focal,now 3.36.0-2ubuntu1 amd64 [installed,automatic]
gnome-sudoku/focal,now 1:3.36.0-1 amd64 [installed,automatic]
gnome-system-monitor/focal-updates,now 3.36.1-0ubuntu0.20.04.1 amd64 [installed,automatic]
gnome-terminal-data/focal-updates,focal-updates,now 3.36.2-1ubuntu1~20.04 all [installed,automatic]
gnome-terminal/focal-updates,now 3.36.2-1ubuntu1~20.04 amd64 [installed,automatic]
gnome-themes-extra-data/focal,focal,now 3.28-1ubuntu1 all [installed,automatic]
gnome-themes-extra/focal,now 3.28-1ubuntu1 amd64 [installed,automatic]
gnome-todo-common/focal,focal,now 3.28.1-5 all [installed,automatic]
gnome-todo/focal,now 3.28.1-5 amd64 [installed,automatic]
gnome-user-docs/focal-updates,focal-updates,now 3.36.2+git20200704-0ubuntu0.1 all [installed,automatic]
gnome-video-effects/focal,focal,now 0.5.0-1ubuntu1 all [installed,automatic]
gnupg-l10n/focal,focal,now 2.2.19-3ubuntu2 all [installed,automatic]
gnupg-utils/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gnupg/focal,focal,now 2.2.19-3ubuntu2 all [installed,automatic]
gpg-agent/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpg-wks-client/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpg-wks-server/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpg/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpgconf/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpgsm/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
gpgv/focal,now 2.2.19-3ubuntu2 amd64 [installed,automatic]
grep/focal,now 3.4-1 amd64 [installed]
grilo-plugins-0.3-base/focal,now 0.3.11-1ubuntu1 amd64 [installed,automatic]
groff-base/focal,now 1.22.4-4build1 amd64 [installed,automatic]
grub-common/focal-updates,now 2.04-1ubuntu26.8 amd64 [installed]
grub-gfxpayload-lists/focal,now 0.7 amd64 [installed]
grub-pc-bin/focal-updates,now 2.04-1ubuntu26.8 amd64 [installed]
grub-pc/focal-updates,now 2.04-1ubuntu26.8 amd64 [installed]
grub2-common/focal-updates,now 2.04-1ubuntu26.8 amd64 [installed]
gsettings-desktop-schemas/focal,focal,now 3.36.0-1ubuntu1 all [installed,automatic]
gsettings-ubuntu-schemas/focal,focal,now 0.0.7+17.10.20170922-0ubuntu1 all [installed,automatic]
gstreamer1.0-alsa/focal,now 1.16.2-4 amd64 [installed,automatic]
gstreamer1.0-clutter-3.0/focal,now 3.0.27-1 amd64 [installed,automatic]
gstreamer1.0-gl/focal,now 1.16.2-4 amd64 [installed,automatic]
gstreamer1.0-gtk3/focal,now 1.16.2-1ubuntu2 amd64 [installed,automatic]
gstreamer1.0-packagekit/focal-updates,focal-security,now 1.1.13-2ubuntu1.1 amd64 [installed,automatic]
gstreamer1.0-plugins-base-apps/focal,now 1.16.2-4 amd64 [installed,automatic]
gstreamer1.0-plugins-base/focal,now 1.16.2-4 amd64 [installed,automatic]
gstreamer1.0-plugins-good/focal,now 1.16.2-1ubuntu2 amd64 [installed,automatic]
gstreamer1.0-pulseaudio/focal,now 1.16.2-1ubuntu2 amd64 [installed,automatic]
gstreamer1.0-tools/focal,now 1.16.2-2 amd64 [installed,automatic]
gstreamer1.0-x/focal,now 1.16.2-4 amd64 [installed,automatic]
gtk-update-icon-cache/focal-updates,now 3.24.20-0ubuntu1 amd64 [installed,automatic]
gtk2-engines-murrine/focal,now 0.98.2-3 amd64 [installed,automatic]
gtk2-engines-pixbuf/focal,now 2.24.32-4ubuntu4 amd64 [installed,automatic]
guile-2.2-libs/focal,now 2.2.7+1-4 amd64 [installed,automatic]
gvfs-backends/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gvfs-bin/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gvfs-common/focal,focal,now 1.44.1-1ubuntu1 all [installed,automatic]
gvfs-daemons/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gvfs-fuse/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gvfs-libs/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gvfs/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
gzip/focal,now 1.10-0ubuntu4 amd64 [installed]
hdparm/focal,now 9.58+ds-4 amd64 [installed,automatic]
hicolor-icon-theme/focal,focal,now 0.17-2 all [installed,automatic]
hostname/focal,now 3.23 amd64 [installed]
hplip-data/focal,focal,now 3.20.3+dfsg0-2 all [installed,automatic]
hplip/focal,now 3.20.3+dfsg0-2 amd64 [installed,automatic]

**Comment by drpresq** [comment]
Issue addressed by commit [2a265](https://github.com/drpresq/cacsupport/commit/2a2650932cb60adebeccf19773dea2ad985bb724)

@charismaticx7 Please retest

**Comment by charismaticx7** [comment]
Still the same issue. Even after running the commands as references.

**Comment by drpresq** [comment]
Issue consolidated into issue #6
